### ISSUE TITLE
Refactor AmrPhysicalAsset

### ISSUE THREAD

**Issue by tseeland** [iml130/sola#16]
Currently used switch-case state handling in `AmrPhysicalAsset` uses more cases than it needs to and only a fixed sequence of actions can be executed with no deviations allowed. To add more flexibility and to allow needed actions that are currently not modelled it would be sensible to use a fsm instead of switch-case.

Also the class `OrderStates` used in the switch-case code tries to fit multiple communication roles:

- logical agent to logical agent and
- physical asset to logical agent

`OrderStates` should be split into two classes/enums.

### TODOs

- [ ] use `fsmlite` in `AmrPhysicalAsset`
- [ ] split `OrderStates` into `TaskEvent` (agent to agent; "something is done") and `TaskExecutionState` (asset to agent; "currently doing something")
- [ ] add necessary functionality `Charge`

`OrderStates` is still used outside of AmrPhysicalAsset and should be deleted at a later date.
